FROM python:3.6.8-alpine

COPY requestments.txt requestments.txt

RUN echo "http://mirrors.aliyun.com/alpine/v3.4/main/" > /etc/apk/repositories && \
    apk add tzdata openssl-dev libffi-dev make gcc g++&& \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    pip install -r requestments.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com && \
    apk add nginx && \
    mkdir /run/nginx && \
    touch /run/nginx/nginx.pid